<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Test Suite" tests="12" assertions="11" failures="7" errors="0" time="8.036518">
    <testsuite name="PhpUnderControl_Example_MathTest" file="tests/SomeTest.php" fullPackage="Example" package="Example" tests="12" assertions="11" failures="7" errors="0" time="8.036518">
      <testcase name="testAddSuccess" class="PhpUnderControl_Example_MathTest" file="tests/SomeTest.php" line="72" assertions="1" time="2.006604"/>
      <testcase name="testSubSuccess" class="PhpUnderControl_Example_MathTest" file="tests/SomeTest.php" line="81" assertions="1" time="0.000842"/>
      <testcase name="testSubFail" class="PhpUnderControl_Example_MathTest" file="tests/SomeTest.php" line="89" assertions="1" time="2.006533">
        <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testSubFail
            Failed asserting that 1 matches expected 0.
        </failure>
      </testcase>
      <testsuite name="PhpUnderControl_Example_MathTest::testDataProviderOneWillFail" tests="4" assertions="4" failures="1" errors="0" time="4.008126">
        <testcase name="testDataProviderOneWillFail with data set #0" assertions="1" time="1.001100"/>
        <testcase name="testDataProviderOneWillFail with data set #1" assertions="1" time="1.001209"/>
        <testcase name="testDataProviderOneWillFail with data set #2" assertions="1" time="1.004137">
          <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testDataProviderOneWillFail with data set #2 (7, 1)
              Failed asserting that 6 matches expected 1.
          </failure>
        </testcase>
        <testcase name="testDataProviderOneWillFail with data set #3" assertions="1" time="1.001680"/>
      </testsuite>
      <testsuite name="PhpUnderControl_Example_MathTest::testDataProviderAllWillFail" tests="4" assertions="4" failures="4" errors="0" time="0.012665">
        <testcase name="testDataProviderAllWillFail with data set #0" assertions="1" time="0.003173">
          <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testDataProviderAllWillFail with data set #0 (17, 42)
            Failed asserting that -25 matches expected 1.

          </failure>
        </testcase>
        <testcase name="testDataProviderAllWillFail with data set #1" assertions="1" time="0.003231">
          <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testDataProviderAllWillFail with data set #1 (13, 23)
            Failed asserting that -10 matches expected 1.
          </failure>
        </testcase>
        <testcase name="testDataProviderAllWillFail with data set #2" assertions="1" time="0.003100">
          <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testDataProviderAllWillFail with data set #2 (42, 17)
            Failed asserting that 25 matches expected 1.
          </failure>
        </testcase>
        <testcase name="testDataProviderAllWillFail with data set #3" assertions="1" time="0.003161">
          <failure type="PHPUnit_Framework_ExpectationFailedException">PhpUnderControl_Example_MathTest::testDataProviderAllWillFail with data set #3 (23, 13)
            Failed asserting that 10 matches expected 1.
          </failure>
        </testcase>
      </testsuite>
      <testcase name="testFail" class="PhpUnderControl_Example_MathTest" file="tests/SomeTest.php" line="119" assertions="0" time="0.001748">
        <failure type="PHPUnit_Framework_AssertionFailedError">PhpUnderControl_Example_MathTest::testFail
          Failed because...
        </failure>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
